spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_programming?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: jpa_programming
    password: 1234!
    dbcp:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
    spring: info


